"""
setup.py — Interactive setup script for the Job Application Agent
Run this ONCE before using the agent for the first time.
Creates your .env file interactively.

Usage: python setup.py
"""
import os
import json
from pathlib import Path


def main():
    print("\n" + "="*60)
    print("  🤖 JOB APPLICATION AGENT — SETUP WIZARD")
    print("="*60)
    print("\nThis wizard will create your .env and user_profile.json files.")
    print("All data stays LOCAL on your computer. Nothing is uploaded.\n")

    env_path = Path(".env")
    if env_path.exists():
        overwrite = input(".env already exists. Overwrite? (y/n): ").lower()
        if overwrite != "y":
            print("Setup cancelled.")
            return

    print("\n--- STEP 1: Gemini API Key ---")
    print("Get your FREE key from: https://aistudio.google.com/app/apikey")
    gemini_key = input("Paste your Gemini API Key: ").strip()

    print("\n--- STEP 2: Gmail Configuration ---")
    print("Use a DEDICATED Gmail for job hunting (e.g., yourname.jobs@gmail.com)")
    print("Get App Password: Gmail → Account → Security → 2FA → App Passwords → Other")
    gmail = input("Your Gmail address: ").strip()
    app_pass = input("Gmail App Password (xxxx xxxx xxxx xxxx): ").strip()

    print("\n--- STEP 3: Portal Credentials (press Enter to skip) ---")
    linkedin_email = input("LinkedIn email (optional): ").strip()
    linkedin_pass = input("LinkedIn password (optional): ").strip()
    naukri_email = input("Naukri email (optional): ").strip()
    naukri_pass = input("Naukri password (optional): ").strip()

    print("\n--- STEP 4: mem0 (optional cloud memory) ---")
    print("Get free API key from: https://mem0.ai")
    mem0_key = input("mem0 API key (optional, press Enter to skip): ").strip()

    print("\n--- STEP 5: Agent Settings ---")
    dry_run = input("Start in DRY RUN mode? (Recommended for first test) [y/n]: ").lower() == "y"
    schedule_hour = input("What hour to run daily? (0-23, default=9): ").strip() or "9"
    max_apply = input("Max jobs to apply per day (default=30): ").strip() or "30"

    # Write .env
    env_content = f"""# Job Application Agent — Environment Variables
# Generated by setup.py — DO NOT commit this file to git

# Gemini AI (FREE from https://aistudio.google.com)
GEMINI_API_KEY={gemini_key}
GEMINI_MODEL=gemini-1.5-flash

# Gmail SMTP
GMAIL_ADDRESS={gmail}
GMAIL_APP_PASSWORD={app_pass}

# mem0 (optional)
MEM0_API_KEY={mem0_key}
MEM0_USER_ID=job_agent_user_001

# LinkedIn (optional)
LINKEDIN_EMAIL={linkedin_email}
LINKEDIN_PASSWORD={linkedin_pass}

# Naukri (optional)
NAUKRI_EMAIL={naukri_email}
NAUKRI_PASSWORD={naukri_pass}

# Agent Settings
DRY_RUN={"True" if dry_run else "False"}
MAX_APPLY_PER_DAY={max_apply}
MAX_EMAIL_PER_DAY=25
SCHEDULE_HOUR={schedule_hour}
SCHEDULE_MINUTE=0
TIMEZONE=Asia/Kolkata
"""
    with open(".env", "w") as f:
        f.write(env_content)

    print("\n✅ .env created!")

    # Guide user to fill in profile
    print("\n--- STEP 6: Update Your Profile ---")
    print("Edit this file with your personal details:")
    print("  → data/user_profile.json")
    print("\nFill in:")
    print("  • Your name, phone, LinkedIn, GitHub, portfolio URL")
    print("  • Your best projects (1-2 lines each)")
    print("  • Put your resume PDF at: data/resume.pdf")

    # Create data directory
    Path("data").mkdir(exist_ok=True)
    Path("logs").mkdir(exist_ok=True)
    Path("database").mkdir(exist_ok=True)

    print("\n" + "="*60)
    print("✅ SETUP COMPLETE!")
    print("="*60)
    print("\nNext steps:")
    print("  1. Edit data/user_profile.json with your details")
    print("  2. Put your resume at: data/resume.pdf")
    print("  3. Test the agent:")
    print("       .\\venv\\Scripts\\python main.py --dry-run")
    print("  4. Once happy, start the daily scheduler:")
    print("       .\\venv\\Scripts\\python main.py")
    print("\nGood luck with your job hunt! 🚀\n")


if __name__ == "__main__":
    main()
